# runner-deployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: opencrvs-infra-runner
  namespace: actions-runner-system
spec:
  replicas: 3
  template:
    spec:
      serviceAccountName: opencrvs-runner
      repository: REPOSITORY_PLACEHOLDER
      image: ghcr.io/opencrvs/opencrvs-github-runner:latest
      labels:
        - self-hosted
        - k8s
        - demo
      env:
        - name: DOCKER_ENABLED
          value: "true"
